# version: '3.8'

# services:
#   postgres:
#     image: postgres:15
#     container_name: ppicker_postgres
#     restart: always
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       APP_USER: ${APP_USER}
#       APP_PASSWORD: ${APP_PASSWORD}
#     ports:
#       - "${POSTGRES_PORT}:5432"
#     volumes:
#       - ./pgdata_prod:/var/lib/postgresql/data
#       - ./init:/docker-entrypoint-initdb.d

# volumes:
#   pgdata_prod:

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d