version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d